version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rcg-test-frontend
    restart: always
    ports:
      - '3000:3000'

  nginx-auth:
    build:
      context: .
      dockerfile: Dockerfile-Nginx
    container_name: nginx-auth
    ports:
      - '80:80'
    depends_on:
      - react-app
